### ISSUE TITLE
Helper creates relative activation/reset links

### ISSUE THREAD

**Issue by bwaidelich** [Flownative/flow-doubleoptin#10]
See https://github.com/neos/Neos.IdNeosIo/issues/10

(I'm not certain that the error resides in this package, but the URI is built [here](https://github.com/flownative/flow-doubleoptin/blob/master/Classes/Helper.php#L169))

**Comment by kdambekalns** [comment]
As explained in neos/Neos.IdNeosIo#10 this needs to be fixed in the userland code, by creating a "proper" request…

This is caused by a recent Flow change. Check if your code does something like this:

            $currentRequestHandler = $this->bootstrap->getActiveRequestHandler();
            if ($currentRequestHandler instanceof HttpRequestHandlerInterface) {
                $httpRequest = $currentRequestHandler->getHttpRequest();
            } else {
                putenv('FLOW_REWRITEURLS=1');
                $httpRequest = Request::createFromEnvironment();
                $httpRequest->setBaseUri(new Uri($this->baseUriSetting));
            }
            $actionRequest = new ActionRequest($httpRequest);
            $this->doubleOptInHelper->setRequest($actionRequest);

and change it to this:

        $currentRequestHandler = $this->bootstrap->getActiveRequestHandler();
        if ($currentRequestHandler instanceof HttpRequestHandlerInterface) {
            $httpRequest = $currentRequestHandler->getHttpRequest();
        } else {
            putenv('FLOW_REWRITEURLS=1');
            $baseUri = new Uri($this->baseUriSetting);
            $httpRequest = Request::create($baseUri, 'POST');
        }
        $actionRequest = new ActionRequest($httpRequest);
        $this->doubleOptInHelper->setRequest($actionRequest);

Note how the `$httpRequest` is built in a different way!

**Comment by bwaidelich** [comment]
The `baseUri` has to be configured for this to work (see https://github.com/neos/Neos.IdNeosIo/pull/12)
